### ISSUE TITLE
RuntimeError: (NotFound) Cannot open file C:\.../inference.pdmodel

### ISSUE THREAD

**Issue by Seminko** [mxtsdev/d4-item-tooltip-ocr#1]
Installed, wanted to try and got this:

```
======================================
Diablo IV: Item Tooltip OCR
======================================

Traceback (most recent call last):
  File "d4-item-tooltip-ocr.py", line 479, in <module>
    jsonstr = it_ocr.processImage(opt.source_img, opt.find_tooltip, debug=False)
  File "d4-item-tooltip-ocr.py", line 183, in processImage
    ocr = PaddleOCR(use_angle_cls=False, lang='en', show_log=False, det_db_unclip_ratio=2.0, rec_model_dir='paddleocr-models/en_PP-OCRv3_rec-d4_tooltip')
  File "C:\Users\myUserName\AppData\Roaming\Python\Python38\site-packages\paddleocr\paddleocr.py", line 523, in __init__
    super().__init__(params)
  File "C:\Users\myUserName\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "C:\Users\myUserName\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\predict_det.py", line 141, in __init__
    self.predictor, self.input_tensor, self.output_tensors, self.config = utility.create_predictor(
  File "C:\Users\myUserName\AppData\Roaming\Python\Python38\site-packages\paddleocr\tools\infer\utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\myUserName/.paddleocr/whl\det\en\en_PP-OCRv3_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2364)
```

I noticed you have included the models under `/en_PP-OCRv3_rec-d4_tooltip` however when I first run the script, it downloads the models anyways:
```
download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to C:\Users\myUserName/.paddleocr/whl\det\en\en_PP-OCRv3_det_infer\en_PP-OCRv3_det_infer.tar
100%|█████████████████████████████████████████████████████████████████████████████| 4.00M/4.00M [00:08<00:00, 447kiB/s]
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to C:\Users\myUserName/.paddleocr/whl\cls\ch_ppocr_mobile_v2.0_cls_infer\ch_ppocr_mobile_v2.0_cls_infer.tar
100%|█████████████████████████████████████████████████████████████████████████████| 2.19M/2.19M [00:11<00:00, 185kiB/s]
```

**Comment by Seminko** [comment]
Managed to fix it.

The issue was non-english character in my windows user since the default path is `C:\Users\<USERNAME>\.paddleocr`

Updated paddleocr.py, put a custom english only directory path in BASE_DIR variable.
